services:
  arbitrage-bot:
    image: 811648613266.dkr.ecr.eu-west-2.amazonaws.com/arbitrage-bot:latest
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
    environment:
      LARAVEL_SAIL: 1
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      APP_NAME: '${APP_NAME}'
      APP_ENV: '${APP_ENV}'
      APP_KEY: '${APP_KEY}'
      APP_DEBUG: '${APP_DEBUG}'
      APP_TIMEZONE: '${APP_TIMEZONE}'
      APP_URL: '${APP_URL}'
      APP_LOCALE: '${APP_LOCALE}'
      APP_FALLBACK_LOCALE: '${APP_FALLBACK_LOCALE}'
      APP_FAKER_LOCALE: '${APP_FAKER_LOCALE}'
      APP_MAINTENANCE_DRIVER: '${APP_MAINTENANCE_DRIVER}'
      APP_MAINTENANCE_STORE: '${APP_MAINTENANCE_STORE}'
      BCRYPT_ROUNDS: '${BCRYPT_ROUNDS}'
      LOG_CHANNEL: '${LOG_CHANNEL}'
      LOG_STACK: '${LOG_STACK}'
      LOG_DEPRECATIONS_CHANNEL: '${LOG_DEPRECATIONS_CHANNEL}'
      LOG_LEVEL: '${LOG_LEVEL}'
      DB_CONNECTION: '${DB_CONNECTION}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      SESSION_DRIVER: '${SESSION_DRIVER}'
      SESSION_LIFETIME: '${SESSION_LIFETIME}'
      SESSION_ENCRYPT: '${SESSION_ENCRYPT}'
      SESSION_PATH: '${SESSION_PATH}'
      SESSION_DOMAIN: '${SESSION_DOMAIN}'
      BROADCAST_CONNECTION: '${BROADCAST_CONNECTION}'
      FILESYSTEM_DISK: '${FILESYSTEM_DISK}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION}'
      CACHE_STORE: '${CACHE_STORE}'
      CACHE_PREFIX: '${CACHE_PREFIX}'
      MEMCACHED_HOST: '${MEMCACHED_HOST}'
      REDIS_CLIENT: '${REDIS_CLIENT}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      REDIS_PORT: '${REDIS_PORT}'
      MAIL_MAILER: '${MAIL_MAILER}'
      MAIL_HOST: '${MAIL_HOST}'
      MAIL_PORT: '${MAIL_PORT}'
      MAIL_USERNAME: '${MAIL_USERNAME}'
      MAIL_PASSWORD: '${MAIL_PASSWORD}'
      MAIL_ENCRYPTION: '${MAIL_ENCRYPTION}'
      MAIL_FROM_ADDRESS: '${MAIL_FROM_ADDRESS}'
      MAIL_FROM_NAME: '${MAIL_FROM_NAME}'
      VITE_APP_NAME: '${VITE_APP_NAME}'
      DISCORD_ALERT_WEBHOOK: '${DISCORD_ALERT_WEBHOOK}'
      DISCORD_API_BOT_TOKEN: '${DISCORD_API_BOT_TOKEN}'
      DISCORD_APPLICATION_ID: '${DISCORD_APPLICATION_ID}'
      DISCORD_PUBLIC_KEY: '${DISCORD_PUBLIC_KEY}'
      DISCORD_CHANNEL_ID: '${DISCORD_CHANNEL_ID}'
      WISE_API_KEY: '${WISE_API_KEY}'
      WISE_RECIPIENT_ID_FOR_REVOLUT: '${WISE_RECIPIENT_ID_FOR_REVOLUT}'
      WISE_OTP_KEY: '${WISE_OTP_KEY}'
      WISE_PIN: '${WISE_PIN}'
      WISE_PROFILE_ID: '${WISE_PROFILE_ID}'
      WISE_EMAIL: '${WISE_EMAIL}'
      WISE_PASSWORD: '${WISE_PASSWORD}'
      WISE_GBP_BALANCE_ID: '${WISE_GBP_BALANCE_ID}'
      WISE_EUR_BALANCE_ID: '${WISE_EUR_BALANCE_ID}'
      KRAKEN_API_KEY: '${KRAKEN_API_KEY}'
      KRAKEN_PRIVATE_KEY: '${KRAKEN_PRIVATE_KEY}'
      KRAKEN_OTP_KEY: '${KRAKEN_OTP_KEY}'
      KRAKEN_USERNAME: '${KRAKEN_USERNAME}'
      KRAKEN_PASSWORD: '${KRAKEN_PASSWORD}'
      IMAP_HOST: '${IMAP_HOST}'
      IMAP_PORT: '${IMAP_PORT}'
      IMAP_ENCRYPTION: '${IMAP_ENCRYPTION}'
      IMAP_VALIDATE_CERT: '${IMAP_VALIDATE_CERT}'
      IMAP_USERNAME: '${IMAP_USERNAME}'
      IMAP_PASSWORD: '${IMAP_PASSWORD}'
      IMAP_DEFAULT_ACCOUNT: '${IMAP_DEFAULT_ACCOUNT}'
      IMAP_PROTOCOL: '${IMAP_PROTOCOL}'
      WWWGROUP: '${WWWGROUP}'
      WWWUSER: '${WWWUSER}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      UMBREL_URL: '${UMBREL_URL}'
      UMBREL_IP: '${UMBREL_IP}'
      UMBREL_PASSWORD: '${UMBREL_PASSWORD}'
      UMBREL_TOTP_KEY: '${UMBREL_TOTP_KEY}'
      HOST_IP: '${HOST_IP}'
      SUAVE_PORT: '${SUAVE_PORT}'
      SUAVE_HOST: '${HOST_IP}'
    volumes:
      - 'sail-laravel:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
  mysql:
    image: 'mysql/mysql-server:8.0'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    environment:
      REDIS_CLIENT: '${REDIS_CLIENT}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      REDIS_PORT: '${REDIS_PORT}'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  # selenium:
  #   image: selenium/standalone-firefox
  #   restart: always
  #   ports:
  #     - '4444:4444'
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   volumes:
  #     - '/dev/shm:/dev/shm'
  #   networks:
  #     - sail
  # mitmproxy:
  #   image: mitmproxy/mitmproxy:latest
  #   restart: always
  #   command: mitmweb --web-host 0.0.0.0
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   volumes:
  #     - ./mitm_certs:/home/mitmproxy/.mitmproxy  # Volume for CA certificates
  #   stdin_open: true   # Equivalent to -it (interactive mode)
  #   tty: true          # Equivalent to -it (pseudo-TTY)
  #   networks:
  #     - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
  sail-laravel:
    driver: local
  sslkeylog:
