name: "Production Deploy"

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: "eu-west-2"
  ECR_REPOSITORY: "arbitrage-bot"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install dependencies for obfuscation
      - name: Install Node.js for Obfuscation
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      # Obfuscate code before Docker build
      - name: Obfuscate code
        run: |
          npm install -g javascript-obfuscator
          javascript-obfuscator src --output src-obfuscated
          mv src-obfuscated src

      - name: Build Docker image
        id: build-image
        run: |
          docker build --file DockerfileProd --tag arbitrage-bot/app .

      - name: Re-login to Amazon ECR
        id: re-login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.re-login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: "latest"
        run: |
          docker tag arbitrage-bot/app ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
